name: Bug Report
description: Use this template to report a bug.
title: "Bug: [Short description]"
labels: ["bug", "pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please describe the bug that you have found in detail. Include any screenshots or error messages that might help.

  - type: input
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
      placeholder: "1. Go to '...'
                       2. Click on '...'
                       3. Scroll down to '...'
                       4. See error"
    validations:
      required: true

  - type: input
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. If applicable, add the version of the software where the bug was found.
