blank_issues_enabled: false  # Disables the option for users to create blank issues
contact_links:
  - name: Asana Project Dashboard
    url: https://app.asana.com/0/1206398263390118/1206398774308628
    about: Please check the Asana Project Dashboard for any open issues.
