name: Caching and artificats
on: [workflow_dispatch]
jobs:
  use-axois:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Cache node modules
          id: cache-dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-npm-cache-
              ${{ runner.os }}-

        # - uses:actions/checkout@v4
        # - uses: actions/stepup-node@v2
        #   with:
        #     node-version: 16
        #     cache: 'npm'

        - name: Display cache output
          run: echo "${{ toJson(steps.cache-dependencies.outputs) }}"
              
        - name: Install dependencies
          run: npm install
        - name: Run Tests
          run: npm test
        - name: Upload Code Coverage Report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: code-coverage
            path: coverage
            retention-days: 10
        - name: Download Code Coverage Report
          uses: actions/download-artifact@v3
          with:
            name: code-coverage
            path: code-coverage-report
        - run: ls -a
        - run: ls -a
          working-directory: code-coverage-report
        - name: Use Axios
          uses: actions/github-script@v7
          with:
            script: |
                const axios = require('axios');
                const response = await axios.get('https://icanhazdadjoke.com/', { headser:{
                    'Accept': 'text/plain'
                }});
                console.log(response.data);