name: Caching and artificats
on: [workflow_dispatch]
jobs:
  use-axois:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install
        - name: Use Axios
          uses: actions/github-script@v6
          with:
            script: |
                const axios = require('axios');
                const response = await axios.get('https://icanhazdadjoke.com/', { headser:{
                    'Accept': 'text/plain'
                }});
                console.log(response.data);