name: concurrenty 2
run-name: concurrenty 2 (${{github.event.inputs.environment}})
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'dev'
                type: environment
concurrency:  # runs only one job with same input at a time
    group: ${{ github.event.inputs.environment }}
    cancel-in-progress: true # cancel any in-progress runs

jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 30