name: concurrenty 1
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'dev'
                type: environment
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 30