name: Send Email Notification

on: [push]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SERVER}}
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        # connection_url: ${{secrets.MAIL_CONNECTION}}
        subject: Github Actions job result
        to: xinlalalele@gmail.com
        from: "Rick Wang <xinlyuwang96@gmail.com>"
        body: Hello from actions
        nodemailerlog: true
        nodemailerdebug: true
