name: Matrix
on:
    [push]
jobs:
    node-matrix:
        continue-on-error: true
        strategy:
            matrix: # run 6 jobs, 2 operating systems and 3 node versions
                os: [ubuntu-latest, windows-latest]
                node-version: [10, 12, 14]
                includes: # merge the matrix with the ralated matrix
                    - os: ubuntu-latest
                      is-ubuntu: true
            # fail-fast: false # do not stop the other jobs if one fails
            # max-parallel: 6   
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v


