name: Send Spreadsheet Email

on: [push]

jobs:
  build_and_send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas pytz
      
    - name: Run script and generate spreadsheet
      id: crawler_script
      run: python hilux-finder.py
 
      
    - name: Send email with spreadsheet attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SERVER}}
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        # connection_url: ${{secrets.MAIL_CONNECTION}}
        subject: Hilux Finder 
        to: xinlalalele@gmail.com
        from: "Rick Wang <xinlyuwang96@gmail.com>"
        body: Hello from actions
        nodemailerlog: true
        nodemailerdebug: true
        attachments: ${{ steps.crawler_script.outputs.excel_path }}