name: Stale Issues & PRs
on:
    # https://crontab.guru/
    schedule:
        # - cron: '0 14 * * *' # At 14:00 on Sunday.
        # - cron: '0/5 * * * *' # Every 5 minutes.
        - cron: '* * 30 10 1' # Test
jobs:
    stale:
        runs-on: unbuntu-latest
        steps:
            - uses: actions/stale@v9
              with:
                stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
                stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
                days-before-stale: 1
                days-before-close: 5