name: Test Api
on: [push, workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/simple-node-api
        ports:
          - 3001:3000
        env:
          MONGO_HOSTNAME: mongo
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Dump Services Context
        run: echo '${{ toJson(job.services) }}'
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users

# name: Test Api
# on: [push, workflow_dispatch]

# jobs:
#   test-api:
#     runs-on: ubuntu-latest
#     container: ubuntu:20.04
#     services:
#       app:
#         image: alialaa17/simple-node-api
#         env:
#           MONGO_HOSTNAME: mongo
#       mongo:
#         image: mongo
#     steps:
#       - name: Install curl
#         run: |
#           apt-get -y update
#           apt-get -y install curl
#       - name: Dump Services Context
#         run: echo '${{ toJson(job.services) }}'
#       - name: Post a user
#         run: 'curl -X POST http://app:3000/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
#       - name: Get Users
#         run: curl http://app:3000/api/users


# name: Build & Publish Docker Image
# on:
#   release:
#     types: [published]

# jobs:
#   push-to-dockerhub-and-ghcr:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v3
#       - name: Login to Dockerhub
#### https://github.com/docker/login-action
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Log in to GHCR
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Extract Metadata
#         id: metadata
#### https://github.com/docker/metadata-action
#         uses: docker/metadata-action@v4
#         with:
#           images: |
#             alialaa17/simple-node-api
#             ghcr.io/${{ github.repository }}
#           tags: |
#             type=semver,pattern={{version}}
#             type=semver,pattern={{major}}.{{minor}}
#       - name: Build & Publish Docker Image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ steps.metadata.outputs.tags }}
#           labels: ${{ steps.metadata.outputs.labels }}