name: Calling Reusable Workflow from another Reusable Workflow
on:
    workflow_dispatch:
        inputs:
            workflow_id:
                description: 'The ID of the workflow to run'
                required: true
                default: 'my-workflow'
                type: string
            workflow_input:
                description: 'The input to pass to the workflow'
                required: false
                type: string
jobs:
    calling-a-reusable-workflow:
        # uses: org_name/repo_name/.github/workflows/reusable-workflow.yml@main
        uses: ./.github/workflows/reusable.yml@main
        with:
            workflow_id: ${{ inputs.workflow_id }}
            workflow_input: ${{ inputs.workflow_input }}
